### ISSUE TITLE
Transaction with Active Record

### ISSUE THREAD

**Issue by pitsolu** [popphp/pop-db#8] opened 2023-12-04 20:32 UTC
I am unable to do transactions with active record

```php
try{

	$db->beginTransaction();

	$role = new Role;
	$role->name = "admin";
	$role->save();
	// first role in db with id 1

	$user = new User;
	$user->name = "tom";
	$user->password = "p@55w0rd";
	$user->role_id = 2; //this role does not exist thus failure
	$user->save();

	$db->commit();
}
catch(Exception $e){

	$db->rollback();
}
```

**Comment by nicksagona** [comment] 2023-12-05 17:36
This is true - it's not currently built into the Active Record class (save, delete, etc methods.) You would have to explicitly call the DB adapter out of the Record class and interact with that outside of the record instance.

However, for the idea of it working directly inside the active record class, tell me what you think of something like this:

**Scenario 1:**
You call the `startTransaction()` method on the active record object. When you call `save()` or `delete()`, it checks if it's in an open transaction and automatically calls `commit()` or - if there's an exception thrown, it will call `rollback()`
```php
$user = new Users([
    'username' => 'testuser',
    'password' => 'password',
    'email'    => 'test@test.com'
]);
$user->startTransaction();
$user->save();
```

**Scenario 2** - same as above, but done with a static method call `start()`:

```php
$user = Users::start([
    'username' => 'testuser',
    'password' => 'password',
    'email'    => 'test@test.com'
]);
$user->save();
```

**Scenario 3** - Working with multiple active record objects whose classes all extend `Pop\Db\Record` - a way to commit all queries that may be executed across multiple AR object instances:

```php
try {
    Record::start();

    $user = new Users([
        'username' => 'testuser',
        'password' => 'password',
        'email'    => 'test@test.com'
    ]);
    $user->save();

    $role = new Roles([
        'role' => 'Admin'
    ]);
    $role->save();

    Record::commit();
} catch (\Exception $e) {
    Record::rollback();
    echo $e->getMessage();
}
```

Let me know your thoughts. I pushed a version of all of this up to the v6-dev branch if you want to check it out.

**Comment by pitsolu** [comment] 2023-12-05 19:19
@nicksagona Whoa! Great responsibility here. Thanks for the honor.

I like scenario 3 looks good.

But may be also add one more scenario:

```php
Record::transaction(function(){

    $user = new Users([
        'username' => 'testuser',
        'password' => 'password',
        'email'    => 'test@test.com'
    ]);
    $user->save();

    $role = new Roles([
        'role' => 'Admin'
    ]);
    $role->save();
});
```

This would work well when you don't have a large chunk of code and you want to be quick.

**Comment by nicksagona** [comment] 2023-12-05 19:56
I like the idea - check out the new commit to `v6-dev`.  Your above code should now work the new `transaction()` method on the Record class.

**Comment by pitsolu** [comment] 2023-12-05 21:52
Both scenarios work perfectly! 

Great job! 

Thanks!

**Comment by nicksagona** [comment] 2023-12-05 21:58
Thanks - I'll marge and cut a new release later today.

**Comment by pitsolu** [comment] 2023-12-05 22:12
Just a thought: You may want to test nested transactions too.

Example: 

```php
Record::transaction(function(){

	$role = new Role([

		"name"=>"test_role"
	]);
	$role->save();

	// throw new Exception("Fail 1!");
	Record::transaction(function(){

		$role = new Role([

			"name"=>"test_role1"
		]);
		$role->save();

		throw new Exception("Fail 2!");

		$user = new User([

			"username"=>"yadmin",
			"password"=>sha1("p@55w0rd$$"),
			"role_id"=>$role->id
		]);
		$user->save();
	});

	$user = new User([

		"username"=>"xadmin",
		"password"=>sha1("p@55w0rd$$"),
		"role_id"=>$role->id
	]);
	$user->save();
});
```

**Comment by martok** [comment] 2023-12-10 22:06
@pitsolu Can I ask, what didn't work about the original code? This is exactly what I've been using before successfully and which doesn't work in 6.1 anymore due to the automatic commit in `Record::save()`.

Stripped down example:
```php
  ChunkedUploads::db()->beginTransaction();
  $upload = new ChunkedUploads([ /* ... */ ]);
  $upload->save();                                          // this would now commit the transaction
  $part = new ChunkedUploadParts([ 'upload_id' => $upload->id, /* ... */ ]);
  $part->save();
  ChunkedUploads::db()->commit();
```

This can be fixed by passing `commit:false` to every single call to `Record::save`, but that seems like a major API change that shouldn't be done in a minor release...

(Also the Adapter-level nested transaction support is currently broken, but I'll open a separate issue for that - #10 )

**Comment by pitsolu** [comment] 2023-12-10 23:45
@martok I believe differently RDBMs' handle transactions differently.

**Comment by martok** [comment] 2023-12-11 09:08
> @martok I believe differently RDBMs' handle transactions differently.

Slightly if we're talking about isolation levels, but not for such elementary use that's part of the standard. Your initial example is correct (unless you're `use`'ing a different `Exception` class from somewhere, now that I think about it?) and should have worked. 
In any case, if it was a DBMS-specific issue, it would still exist...

**Comment by nicksagona** [comment] 2023-12-11 15:15
Hey everyone - reopened the issue in light of what's has been brought up by @martok. I have some things to take care of at work this morning and then I was planning on taking a look at the issues and scenarios talked about here.

**Comment by nicksagona** [comment] 2023-12-13 04:53
Actually - @martok  - I just looked over the scenario you brought up. I came across that very situation and what was implemented in v6.2.0 should take care of it. There are separate flags that track where the transaction was started: either by a DB adapter (outside of the Record namespace) OR within the Record namespace. For example, using v6.2.0, this code works as expected:

```php
$db->beginTransaction();

$user = new Users([
    'username' => 'testuser',
    'password' => '12345678',
    'email'    => 'testuser@test.com'
]);

$user->save(); // Transaction DOES NOT commit/save here

$db->commit(); // Transaction DOES commit/save here.
```

Try updating to v6.2.0 and let me know if your code above works as it should.

**Comment by martok** [comment] 2023-12-13 09:03
I'll need to trace it through and draw a diagram after work today... At the very least, there's some inconsistent duplication between the AbstractRecord instance methods and the Record static methods and the Adapter that does not look like it can work reliably.

**Comment by martok** [comment] 2023-12-14 00:00
Alright, review complete. I did in fact draw a [diagram](https://github.com/popphp/pop-db/assets/109197/852e26ad-7192-4cd1-a7e7-a8dfc61f0b90)...
So, good news: if you never call `Record::start` or `record->startTransaction` and use the Adapter directly, nothing changes and my code indeed still works, as you said. But there's a few issues...

Using the static methods looks like it works because only the wrapper codepaths to the `AbstractAdapter` methods are actually called. `Record::start` calls into a new instance's `startTransaction` which then increases the adapter's nesting level, but that instance is then thrown away so the nesting stack will never resolve correctly. `Record::rollback` itself is only allowed if no transaction nesting is active as seen by the Adapter, which (as `start => startTransaction` causes a double-count) implies that `Record::start` _wasn't_ used. However, `Record::commit` is always allowed.

A record instance's `commitTransaction` and `rollbackTransaction` are only called from `save`/`delete` iff the same instance's `startTransaction` was previously called directly (as the static call would set the flag on a throwaway instance). So basically never...

And also commenting on 6.3.0, as per your [comment on #10](https://github.com/popphp/pop-db/issues/10#issuecomment-1853311767), since that's the version I checked anyway.
Immediately setting the `transactionDepth` to 0 on `rollback` (and `Pgsql->commit`, that looks like an error, the others don't) will lead to issues if any of the outer transactions also call "commit", as that then gives negative `transactionDepth` which any further `adapter->beginTransaction` will then first have to increment over.

Since I've got all this stuck in my head out now anyway, if you don't veto it I'll work on a PR to resolve all those.

**Comment by nicksagona** [comment] 2023-12-14 00:33
So the intention is that one or the other is used to manage the transactions - but not both:

1. Either the DB adapter manages the transactions - even if you make calls with the Record class in between, OR
2. The Record class manages the transactions - even if you make queries with the DB adapter in between

The two of them (the DB adapter and the Record class) should not be used together to manage transactions b/c that will cause the conflict you outlined above.

With that in mind, the attempt was to satisfy both scenarios. However, I do see the additional issues you've outlined. You're more than welcome to work on a PR for it. I'm going investigate more some myself when I have some time.

Also - thanks for the catch on the Pgsql adapter commit - already pushed a patch up for that.

**Comment by nicksagona** [comment] 2023-12-14 01:11
@martok - I just pushed up a small change to v6-dev that may have addressed the issue, or at least one of them. The `$db->beginTransaction` was getting "double-called" in the `Record::start()` method. It was getting called explicitly, and then again down in the `$record->startTransaction()` call right after. That was definitely throwing off the depth index. So with the patch up on v6-dev now this code works as expected (it's the inverse of my example above - the Record class starts the transaction and some pure DB transaction/queries are made in between):

```php
$user = Users::start([
    'username' => 'testuser1',
    'password' => '12345678',
    'email'    => 'testuser1@test.com'
]);

$db->beginTransaction();
$db->query("INSERT INTO `users`...");
$db->commit();   // Does not commit

$role = new Roles([
    'role' => 'Admin'
]);
$role->startTransaction();

$role->save();   // Does not commit

$db->beginTransaction();
$db->query("INSERT INTO `users` ...");
$db->commit();  // Does not commit
$user->save(); // Commits all queries
```

Let me know your thoughts on this if you have a minute. Thanks.

**Comment by martok** [comment] 2023-12-14 10:10
> (it's the inverse of my example above - the Record class starts the transaction and some pure DB transaction/queries are made in between):

Aaah, now I see how that is supposed to be used. I don't quite understand the rationale, but it should work. Just a few small kinks, then!

**Comment by nicksagona** [comment] 2023-12-14 14:28
@martok - so everything working as expected now for you? Good to close out the two issues?

I actually think the statement I made earlier is no longer true (which is a good thing):

> So the intention is that one or the other is used to manage the transactions - but not both:

now that the internal tracking of transaction depth is patched/improved between the DB adapters and the Record class.

**Comment by martok** [comment] 2023-12-14 15:31
@nicksagona I wouldn't say as expected, but as designed 😉 So yeah, go ahead and close as resolved.

I'll propose a few more changes for robustness and documentation, but it won't change the API interface or logic.

**Comment by nicksagona** [comment] 2023-12-14 15:40
Good deal. Thanks for your input on this.

**Closed as completed by nicksagona** 2023-12-14 15:40 UTC
